### ISSUE TITLE
Not compatible with Fastboot

### ISSUE THREAD

**Issue by bttf** [ember-cli/ember-welcome-page#28]
ember-cli-fastboot v0.6.2
ember-cli 2.6.0-beta.2

Newly created app is rendered as blank after running

```
ember fastboot --serve-assets
```

and accessing `localhost:3000`.

Console errors are about assets not being available (css/js files).

**Comment by stefanpenner** [comment]
cc @tomdale, @acorncom

**Comment by acorncom** [comment]
Given the fact that we're hijacking Express with this add-on (by taking over completely if our criteria are met), it would make sense that it's not working exactly right ...  My preference might be to completely disable this add-on if run through Fastboot, but we would then not be serving things identically to what folks see without Fastboot.

@tomdale I wonder about just by-passing Fastboot completely in this add-on (if Fastboot is detected).  Otherwise, we'll have to feed the [results we're generating here](https://github.com/ember-cli/ember-welcome-page/blob/master/index.js#L52-L58) back into Fastboot somehow ...  Thoughts?

**Comment by locks** [comment]
As I see it, it would make sense for the welcome page to not be seen from FastBoot, as FastBoot shows what a "production" user would see. Conceptually it would make sense for FastBoot to provide its own welcome-page, possibly with instructions more specific to FastBoot.

**Comment by acorncom** [comment]
It might be worth considering doing Fastboot-specific instructions here if we're going to use the same template / design to save on duplication.  But if it'd be better to have different branding, etc than an entirely different page / add-on seems to make more sense ...

**Comment by acorncom** [comment]
@bttf Do you get errors if you have an `application.hbs` file or any routes defined?  Or does this only occur if you're starting a brand-new app up from scratch and haven't yet setup an app?

**Comment by jasonmit** [comment]
I believe this was resolved by the changes in 2.0.0.  I'll validate that and report back.

**Comment by jasonmit** [comment]
Update, yup all fixed.

Unrelated but noticed this while setting up a demo against ^2.0.0, ember-welcome-page should include a blueprint which adds `{{welcome-page}}` into `application.hbs`.  Want me to PR that?

**Comment by locks** [comment]
@jasonmit appreciated, but the blueprint actually needs to be generated with the app, see https://github.com/ember-cli/ember-cli/pull/6378 :)

**Comment by pavolatzonky** [comment]
For anyone seeing this stacktrace in their fastboot starter fastboot app, welcome page component is missing in the prod build:

```There was an error running your app in fastboot. More info about the error:
 TypeError: Cannot destructure property 'manager' of 'e' as it is null.
    at u.resolvedComponent (/Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:2464:28)
    at /Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:2359:5
    at ie (/Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:2359:30)
    at l (/Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:2350:1)
    at /Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:2325:6
    at _.compile (/Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:2260:173)
    at te (/Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:2350:44)
    at /Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:2346:30
    at Z.compile (/Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:2347:23)
    at Object.evaluate (/Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:2826:224)
    at Object.evaluate (/Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:2633:13)
    at It.evaluateSyscall (/Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:2934:61)
    at It.evaluateInner (/Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:2928:138)
    at It.evaluateOuter (/Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:2928:59)
    at Wt.next (/Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:2989:26)
    at Wt._execute (/Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:2988:25)
    at Wt.execute (/Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:2987:298)
    at Qt.sync (/Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:2991:86)
    at _r.render (/Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:566:546)
    at /Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:592:31
    at Nt (/Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:2924:5)
    at Pr._renderRoots (/Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:591:34)
    at Pr._renderRootsTransaction (/Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:596:10)
    at Pr._renderRoot (/Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:590:50)
    at Pr._appendDefinition (/Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:585:6)
    at Pr.appendOutletView (/Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:583:6)
    at invokeWithOnError (/Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:3333:206)
    at h.flush (/Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:3325:74)
    at p.flush (/Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:3338:207)
    at B._end (/Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:3395:9)
    at B._boundAutorunEnd (/Users/puwel/Development/xamoom/client-prototype/dist/assets/vendor-cebbad065d28def16d70c7d49317aaf4.js:3347:605)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)```
